package libs

const val FRAGMENT_KTX = "1.5.7"
const val APP_COMPAT = "1.6.1"
const val CORE_KTX = "1.12.0"
const val RUNTIME_KTX = "2.3.1"
const val LIFECYCLE_RUNTIME_KTX = "2.6.2"
const val ACTIVITY_COMOPSE = "1.7.2"
const val COMPOSE_VERSION = "1.5.1"
const val MATERIAL = "1.2.0"
const val NAV_VERSION = "2.7.2"
const val FIREBASE_BOM = "32.1.0"
const val FIREBASE_AUTH = "22.1.2"
const val TIMBER_VERSION = "5.0.1"
const val COIL_COMPOSE = "2.2.2"
const val ACCOMPANIST_PAGER = "0.22.0-rc"
const val CONSTRAINT_COMPOSE_VERSION = "1.0.1"
const val HILT_VERSION = "2.45"
const val HILT_COMPILER_VERSION = "1.0.0"
const val HILT_NAVIGATION_COMPOSE_VERSION = "1.0.0"
const val MOSHI_VERSION = "1.15.0"
const val DETEKT_VERSION = "1.3.0"
const val LIFECYCLE_KTX = "2.6.1"
const val WEBKIT_VERSION = "1.6.1"
